import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  { ignores: ["dist", "coverage", "src/core/api/schema.d.ts"] },
  js.configs.recommended,
  tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true },
      ],
    },
  },
  {
    // Vendored shadcn/ui code (generated by the CLI, not hand-maintained).
    // Relax the React Compiler lint rules it trips; keep app code strict.
    files: ["src/components/ui/**", "src/hooks/use-mobile.ts"],
    rules: {
      "react-hooks/purity": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-refresh/only-export-components": "off",
    },
  },
  {
    // Barrels, route definitions, and app composition intentionally export a
    // mix of components and non-components; they are not Fast Refresh boundaries.
    files: ["**/index.ts", "**/routes.{ts,tsx}", "src/app/**"],
    rules: { "react-refresh/only-export-components": "off" },
  },
  {
    // Tests and the test harness run under Vitest + Node.
    files: ["**/*.test.{ts,tsx}", "src/test/**"],
    languageOptions: { globals: { ...globals.node } },
    rules: { "react-refresh/only-export-components": "off" },
  },
);
