"""create properties table

Revision ID: f465fbacd3cb
Revises: 9fa5446bf034
Create Date: 2026-07-05 14:54:33.480695

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f465fbacd3cb"
down_revision: str | Sequence[str] | None = "9fa5446bf034"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "properties",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_properties_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_properties_organization_id"),
            ["organization_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_properties_organization_id"))
        batch_op.drop_index(batch_op.f("ix_properties_name"))

    op.drop_table("properties")
    # ### end Alembic commands ###
