"""add name and contact fields to users

Revision ID: 00a6b70d613e
Revises: 26fe4980fd56
Create Date: 2026-07-05 13:37:45.492531

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00a6b70d613e"
down_revision: str | Sequence[str] | None = "26fe4980fd56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("first_name", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("last_name", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("email", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("phone", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_column("phone")
        batch_op.drop_column("email")
        batch_op.drop_column("last_name")
        batch_op.drop_column("first_name")

    # ### end Alembic commands ###
