"""drop name column from users

Revision ID: 18ae89567f9e
Revises: 00a6b70d613e
Create Date: 2026-07-05 13:39:16.328951

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18ae89567f9e"
down_revision: str | Sequence[str] | None = "00a6b70d613e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_name"))
        batch_op.drop_column("name")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f("ix_users_name"), ["name"], unique=False)

    # ### end Alembic commands ###
