"""add unique property name per org and unit name per property

Revision ID: 19b7d807824d
Revises: c3d4e5f6a7b8
Create Date: 2026-07-14 22:42:01.278416

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19b7d807824d"
down_revision: str | Sequence[str] | None = "c3d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.create_index(
            "uq_properties_org_name",
            ["organization_id", "name"],
            unique=True,
            postgresql_where=sa.text("deleted_at IS NULL"),
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.create_index(
            "uq_units_property_name",
            ["property_id", "name"],
            unique=True,
            postgresql_where=sa.text("deleted_at IS NULL"),
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_units_property_name",
            postgresql_where=sa.text("deleted_at IS NULL"),
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_properties_org_name",
            postgresql_where=sa.text("deleted_at IS NULL"),
            sqlite_where=sa.text("deleted_at IS NULL"),
        )

    # ### end Alembic commands ###
