"""create lease_terms table

Revision ID: 1b4a7577c918
Revises: 1e48b2e796fa
Create Date: 2026-07-06 15:58:21.847655

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b4a7577c918"
down_revision: str | Sequence[str] | None = "1e48b2e796fa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lease_terms",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("interval", sa.String(), nullable=False),
        sa.Column("lease_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["leases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lease_terms", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lease_terms_lease_id"), ["lease_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lease_terms_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lease_terms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lease_terms_name"))
        batch_op.drop_index(batch_op.f("ix_lease_terms_lease_id"))

    op.drop_table("lease_terms")
    # ### end Alembic commands ###
