"""add effective_from and terminated_on to leases

Revision ID: 1e48b2e796fa
Revises: 3469e2ef0844
Create Date: 2026-07-06 15:53:13.196908

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e48b2e796fa"
down_revision: str | Sequence[str] | None = "3469e2ef0844"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False)
        )
        batch_op.add_column(
            sa.Column("terminated_on", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leases", schema=None) as batch_op:
        batch_op.drop_column("terminated_on")
        batch_op.drop_column("effective_from")

    # ### end Alembic commands ###
