"""create lease_deposits table

Revision ID: 3469e2ef0844
Revises: b846d99257fc
Create Date: 2026-07-06 15:49:23.258595

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3469e2ef0844"
down_revision: str | Sequence[str] | None = "b846d99257fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lease_deposits",
        sa.Column("lease_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["lease_id"],
            ["leases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("lease_deposits", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lease_deposits_lease_id"), ["lease_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lease_deposits", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lease_deposits_lease_id"))

    op.drop_table("lease_deposits")
    # ### end Alembic commands ###
