"""add partial unique index for one active lease per unit

Revision ID: 456bbcac1c4d
Revises: 1b4a7577c918
Create Date: 2026-07-06 16:39:04.083348

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "456bbcac1c4d"
down_revision: str | Sequence[str] | None = "1b4a7577c918"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leases", schema=None) as batch_op:
        batch_op.create_index(
            "uq_leases_active_unit",
            ["unit_id"],
            unique=True,
            postgresql_where=sa.text("terminated_on IS NULL AND deleted_at IS NULL"),
            sqlite_where=sa.text("terminated_on IS NULL AND deleted_at IS NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leases", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_leases_active_unit",
            postgresql_where=sa.text("terminated_on IS NULL AND deleted_at IS NULL"),
            sqlite_where=sa.text("terminated_on IS NULL AND deleted_at IS NULL"),
        )

    # ### end Alembic commands ###
