"""create units table

Revision ID: 6b4dc73838e0
Revises: f465fbacd3cb
Create Date: 2026-07-05 14:55:42.507995

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b4dc73838e0"
down_revision: str | Sequence[str] | None = "f465fbacd3cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_units_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_units_property_id"), ["property_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("units", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_units_property_id"))
        batch_op.drop_index(batch_op.f("ix_units_name"))

    op.drop_table("units")
    # ### end Alembic commands ###
