"""add rate to lease_terms

Revision ID: 8f4a6197f3fc
Revises: c7e91a4b0d23
Create Date: 2026-07-10 23:45:37.089681

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8f4a6197f3fc'
down_revision: str | Sequence[str] | None = 'c7e91a4b0d23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lease_terms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "rate",
                sa.Enum("variable", "fixed", name="ratetype", native_enum=False),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lease_terms", schema=None) as batch_op:
        batch_op.drop_column("rate")

    # ### end Alembic commands ###
