"""add type to lease_terms

Revision ID: a1b2c3d4e5f6
Revises: ed9ada0c0a6a
Create Date: 2026-07-14 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | Sequence[str] | None = "ed9ada0c0a6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lease_terms", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type",
                sa.Enum("prepaid", "postpaid", name="paymenttype", native_enum=False),
                nullable=False,
                # Backfill existing rows; new rows always supply a value.
                server_default="prepaid",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lease_terms", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###
