"""create leases table

Revision ID: b846d99257fc
Revises: 6b4dc73838e0
Create Date: 2026-07-06 15:27:10.927940

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b846d99257fc"
down_revision: str | Sequence[str] | None = "6b4dc73838e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "leases",
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["user_accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("leases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_leases_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_leases_unit_id"), ["unit_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leases_unit_id"))
        batch_op.drop_index(batch_op.f("ix_leases_account_id"))

    op.drop_table("leases")
    # ### end Alembic commands ###
