"""create user_accounts table

Revision ID: ba23839a667d
Revises: 18ae89567f9e
Create Date: 2026-07-05 13:41:33.852666

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba23839a667d"
down_revision: str | Sequence[str] | None = "18ae89567f9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_accounts_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_accounts_user_id"))

    op.drop_table("user_accounts")
    # ### end Alembic commands ###
