"""create bill_items table

Revision ID: ed9ada0c0a6a
Revises: 55e66308f0cf
Create Date: 2026-07-11 15:02:40.976536

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed9ada0c0a6a"
down_revision: str | Sequence[str] | None = "55e66308f0cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_items",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("bill_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bill_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bill_items_bill_id"), ["bill_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_bill_items_name"), ["name"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bill_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bill_items_name"))
        batch_op.drop_index(batch_op.f("ix_bill_items_bill_id"))

    op.drop_table("bill_items")
    # ### end Alembic commands ###
